name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch name if it's not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14


    - name: Build project
      run: npm run build  # Replace this with your build command if it's different

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Replace this with your output folder if it's different
